### ISSUE TITLE
Add command to post pictures of an old person

### ISSUE THREAD

**Issue by cargillj** [cargillj/OldMan#1]
**Is your feature request related to a problem? Please describe.**
I need more old people in my life.

**Describe the solution you'd like**
I want a command like this:
`$pic` - sends a message to the channel containing a picture of an old person. The picture should be dynamic and coming from a service.

![Grandma-Finds-The-Internet](https://user-images.githubusercontent.com/5783425/68002474-4a7a5a00-fc26-11e9-82e6-7f89636aac2e.jpg)

**Comment by arby316** [comment]
some people and their weird fetishes...

**Comment by ssp0929** [comment]
WHOA

**Comment by cargillj** [comment]
> some people and their weird fetishes...

Ok, **boomer**
