### ISSUE TITLE
I want OldMan to tell me about events happening in his life

### ISSUE THREAD

**Issue by cargillj** [cargillj/OldMan#2]
**Is your feature request related to a problem? Please describe.**
OldMan has an eventful life, I want him to tell the chat when something happens.

**Describe the solution you'd like**
OldMan should randomly generate life events and comment on them in chat:
```
OldMan: "I fell and broke my hip today, installing handlebars in the tub!"
OldMan: "I've been diagnosed with [disease]!"
OldMan: "I was looking at the facebook today and saw this great post: [typical boomer post]"
```

**Comment by cargillj** [comment]
Possibly use [cron-schedule](https://www.npmjs.com/package/node-schedule) to schedule events.

**Comment by ssp0929** [comment]
No that's a bad idea.
